all: BTMS_Repon
BTMS_Repon: add.o add_staff.o blood.o delete.o delete_staff.o doctor.o Introduction.o list.o list_staff.o main.o mew.o modify.o modify_staff.o option.o patient.o print.o print_staff.o read.o restore.o restore_staff.o search.o search_staff.o staff.o
	g++ add.o add_staff.o blood.o delete.o delete_staff.o doctor.o Introduction.o list.o list_staff.o main.o mew.o modify.o modify_staff.o option.o patient.o print.o print_staff.o read.o restore.o restore_staff.o search.o search_staff.o staff.o -o Dream_mak
add.o: add.c
	g++ -c add.c
add_staff.o: add_staff.c
	g++ -c add_staff.c
blood.o: blood.c
	g++ -c blood.c
delete.o: delete.o
	g++ -c delete.c
delete_staff.o: delete_staff.c
	g++ -c delete_staff.c
doctor.o: doctor.c
	g++ -c doctor.c
Introduction.o: Introduction.c
	g++ -c Introduction.c
list.o: list.c
	g++ -c list.c
list_staff.o: list_staff.c
	g++ -c list_staff.c
main.o: main.c
	g++ -c main.c
mew.o: mew.c
	g++ -c mew.c
modify.o: modify.c
	g++ -c modify.c
modify_staff.o: modify_staff.c
	g++ -c modify_staff.c
option.o: option.c
	g++ -c option.c
patient.o: patient.c
	g++ -c patient.c
print.o: print.c
	g++ -c print.c
print_staff.o: print_staff.c
	g++ -c print_staff.c

read.o: read.c
	g++ -c read.c
restore.o: restore.c
	g++ -c restore.c
restore_staff.o: restore_staff.c
	g++ -c restore_staff.c
search.o: search.c
	g++ -c search.c
search_staff.o: search_staff.c
	g++ -c search_staff.c
staff.o: staff.c
	g++ -c staff.c
clean:
	del *.o *.exe
rebuild:
	clean all